language: php

php:
  - 5.4
  - 5.5
  - hhvm

install:
  - composer self-update && composer --version
  - composer install --dev --prefer-dist

script:
  - vendor/bin/phpunit --verbose --coverate-text
